/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swami2020

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
//        val classUnderTest = App()
        assertNotNull("Test stuff")
    }
}
