/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swami2020

import org.http4k.client.OkHttp
import org.http4k.core.Body
import org.http4k.core.Method
import org.http4k.core.Request
import org.http4k.core.Status
import org.http4k.format.Jackson.auto
import swami2020.response.Team
import java.util.*
import kotlin.test.*

class AppTest {
    private val port = 9000
    private val client = OkHttp()

    private val teamLens = Body.auto<Team>().toLens()
    private val teamListLens = Body.auto<Collection<Team>>().toLens()

    private val testTeam = Team(
            UUID.fromString("9579145e-1946-4f42-9c47-42fefb4eb8e6"),
            "Iowa",
            "Hawkeyes",
            "Big Ten"
    )

    lateinit var app : App

    @BeforeTest fun setup() {
        val databaseProperties = Properties()
        databaseProperties.setProperty("jdbcUrl", "jdbc:postgresql://localhost:5432/swami")
        databaseProperties.setProperty("username", "swami_user")
        databaseProperties.setProperty("password", "Password_1")

        // Server
        val serverProperties = Properties()
        serverProperties.setProperty("port", "$port")

        val swamiProperties = SwamiProperties()
        swamiProperties.database = databaseProperties
        swamiProperties.server = serverProperties
        val appFactory = AppFactory(swamiProperties)
        app = App(appFactory)
        app.start()
    }

    @AfterTest fun teardown() {
        app.stop()
    }

    @Test fun testHealth() {
        val resp = client(Request(Method.GET, "http://localhost:$port/hello/jonny"))
        assertNotNull(resp)
        assertEquals(Status.OK, resp.status)
        assertEquals("Hello, jonny!", resp.bodyString())
    }

    @Test fun testTeamList() {
        val resp = client(Request(Method.GET, "http://localhost:$port/teams"))
        assertNotNull(resp)
        assertEquals(Status.OK, resp.status)

        val teams = teamListLens(resp)

        assertEquals(50, teams?.size)
        teams.forEach { team ->
            assertNotNull(team.id)
            assertNotNull(team.name)
            assertNotNull(team.nickName)
            assertNotNull(team.conference)
        }
    }

    @Test fun testTeamFetch() {
        val resp = client(Request(Method.GET, "http://localhost:$port/teams/${testTeam.id.toString()}"))
        assertNotNull(resp)
        assertEquals(Status.OK, resp.status)

        val team = teamLens(resp)
        assertEquals(testTeam, team)
    }
}
