/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.70"

    // Flyway
    id("org.flywaydb.flyway") version "5.2.4"

    // Apply the application plugin to add support for building a CLI application.
    application
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath("com.github.jengelman.gradle.plugins:shadow:5.0.0")
        classpath("org.postgresql:postgresql:42.2.1")
    }
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // HTTP4k
    implementation("org.http4k:http4k-core:3.245.0")
    implementation("org.http4k:http4k-server-jetty:3.245.0")
    implementation("org.http4k:http4k-client-apache:3.245.0")

    // Flyway
    implementation("org.flywaydb:flyway-core:6.4.1")

    // Postresql
    implementation("org.postgresql:postgresql:42.2.1")

    // Jackson
    implementation("org.http4k:http4k-format-jackson:3.245.1")

}

flyway {
    url = "jdbc:postgresql://127.0.0.1:5432/swami"
    user = "swami_user"
    password = "Password1"
}

application {
    // Define the main class for the application.
    mainClassName = "swami2020.AppKt"
}

tasks.named("run") {
    dependsOn(":flywayMigrate")
}
